version: '3'

services:
  # Service pour l'application Node.js
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/
    depends_on:
      - db
    environment:
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase

  # Service pour la base de données MySQL
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
